### ISSUE TITLE
Python3.6

### ISSUE THREAD

**Issue by paternal** [redjack/docker-pythons#1]
Hello,
now that [python3.6 is out](http://blog.python.org/2016/12/python-360-is-now-available.html), do you have any plan to integrate it to this docker image, or should I look elsewhere or fork this project?
Regards,
Louis

**Comment by rouge8** [comment]
I'm no longer at RedJack, so I'm not sure if anyone is still using this. Unfortunately, the apt repositories we used are no longer maintained, so updating it could be complicated:

- https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
- https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7

**Comment by paternal** [comment]
Ok. Thanks anyway…

**Comment by paternal** [comment]
For information, those wanting a docker image with several python version can use:

- [rouge8](//hub.docker.com/r/rouge8/pythons): Based on Ubuntu 14.04 LTS, with Python 2.6, 2.7, 3.3, 3.4, 3.5, and PyPy.
- [paternal](//hub.docker.com/r/paternal/pythons): Based on Debian Stable, with Python 2.7, 3.4, 3.5, 3.6, pypy, jython.
